### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by BechirAhmed** [WrathChaos/react-native-star-review#4]
Great work.
It'll be better if we could set the increment value (0.1 or whatever the user want) instead of 1 as default, disable reviews just like enableStare.
Just add more customizations.

**Comment by kuraydev** [comment]
Hello @BechirAhmed,
Thank you for this awesome feedback. I'm going to make these enhancements ASAP. I will inform you when it's done. 

Just one little thing, unfortunately, I could not make the incremental value float. If you have any idea or make it work. I'm open for PR :)

Gonna make it fully customizable and make the disable feature for reviews ASAP

**Comment by BechirAhmed** [comment]
Thanks @WrathChaos , I don't have any clear idea on how to do that, but maybe this link can give you idea: https://github.com/Extrct/react-native-stars/blob/master/index.js

**Comment by kuraydev** [comment]
Thank you @BechirAhmed, 
First, I'm going to develop other enhancements then working on incremental value stuff.

**Comment by kuraydev** [comment]
Hello again @BechirAhmed,
I've updated the library. Could not find much more customizable but disableReview prop is integrated :) 

If you have a proper solution for incremental value problem, please open an issue. Also, PR's are always welcome 😇

Here is the new version: 

## [Release 0.0.3 🎉🎊](https://github.com/WrathChaos/react-native-star-review/releases/tag/0.0.3)

**Comment by BechirAhmed** [comment]
Super, thanks @WrathChaos, I’ll when i found a proper solution for it. Thanks again
